/**
 * Client-side image preprocessing before sending to the backend.
 * Resizes to max 1024×1024 conserving aspect ratio and converts to PNG base64.
 */

/**
 * Removes white/near-white background from an image and returns a transparent PNG data URL.
 * Works purely in the browser via canvas pixel manipulation — no server call needed.
 *
 * Algorithm: for each pixel, compute minChannel = min(R, G, B).
 *   - minChannel >= threshold           → fully transparent
 *   - threshold > minChannel >= threshold-fadeZone → soft alpha fade (anti-alias)
 *   - below fade zone                   → fully opaque
 *
 * This preserves all colored fur/art while cleanly removing the pure white bg
 * generated by FLUX and present in the demo Border Terrier.
 */
export async function removeWhiteBackground(
  url: string,
  threshold = 238,
  fadeZone = 25,
): Promise<string> {
  return new Promise((resolve) => {
    const img = new window.Image()
    img.crossOrigin = 'anonymous'

    img.onload = () => {
      try {
        const canvas = document.createElement('canvas')
        canvas.width  = img.naturalWidth
        canvas.height = img.naturalHeight
        const ctx = canvas.getContext('2d')!
        ctx.drawImage(img, 0, 0)

        const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height)
        const d = imageData.data

        for (let i = 0; i < d.length; i += 4) {
          const r = d[i], g = d[i + 1], b = d[i + 2]
          const minC = Math.min(r, g, b)

          if (minC >= threshold) {
            // Fully white or near-white → transparent
            d[i + 3] = 0
          } else if (minC >= threshold - fadeZone) {
            // Soft fade zone for clean anti-aliased edges
            const t = (minC - (threshold - fadeZone)) / fadeZone
            d[i + 3] = Math.round((1 - t) * d[i + 3])
          }
          // else: keep fully opaque
        }

        ctx.putImageData(imageData, 0, 0)
        resolve(canvas.toDataURL('image/png'))
      } catch {
        // Canvas tainted by CORS or other error → fall back to original URL
        resolve(url)
      }
    }

    img.onerror = () => resolve(url)
    img.src = url
  })
}

export async function compressAndResizeImage(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const img = new window.Image()
    const objectUrl = URL.createObjectURL(file)

    img.onload = () => {
      URL.revokeObjectURL(objectUrl)

      const MAX = 1024
      let { width, height } = img

      if (width > MAX || height > MAX) {
        if (width >= height) {
          height = Math.round((height * MAX) / width)
          width = MAX
        } else {
          width = Math.round((width * MAX) / height)
          height = MAX
        }
      }

      const canvas = document.createElement('canvas')
      canvas.width = width
      canvas.height = height
      const ctx = canvas.getContext('2d')!
      ctx.drawImage(img, 0, 0, width, height)

      // PNG preserves quality for edge detection; strip the data URI prefix
      const dataUrl = canvas.toDataURL('image/png')
      resolve(dataUrl.replace(/^data:image\/png;base64,/, ''))
    }

    img.onerror = () => reject(new Error('No se pudo cargar la imagen para comprimir'))
    img.src = objectUrl
  })
}