/**
 * Client-side image preprocessing before sending to the backend.
 * Resizes to max 1024×1024 conserving aspect ratio and converts to PNG base64.
 */

/**
 * Removes white/near-white background from an image and returns a transparent PNG data URL.
 * Works purely in the browser via canvas pixel manipulation — no server call needed.
 *
 * Algorithm: for each pixel, compute minChannel = min(R, G, B).
 *   - minChannel >= threshold           → fully transparent
 *   - threshold > minChannel >= threshold-fadeZone → soft alpha fade (anti-alias)
 *   - below fade zone                   → fully opaque
 *
 * This preserves all colored fur/art while cleanly removing the pure white bg
 * generated by FLUX and present in the demo Border Terrier.
 */
export async function removeWhiteBackground(
  url: string,
  threshold = 238,
  fadeZone = 25,
): Promise<string> {
  return new Promise((resolve) => {
    const img = new window.Image()
    img.crossOrigin = 'anonymous'

    img.onload = () => {
      try {
        const canvas = document.createElement('canvas')
        canvas.width  = img.naturalWidth
        canvas.height = img.naturalHeight
        const ctx = canvas.getContext('2d')!
        ctx.drawImage(img, 0, 0)

        const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height)
        const d = imageData.data

        for (let i = 0; i < d.length; i += 4) {
          const r = d[i], g = d[i + 1], b = d[i + 2]
          const minC = Math.min(r, g, b)

          if (minC >= threshold) {
            // Fully white or near-white → transparent
            d[i + 3] = 0
          } else if (minC >= threshold - fadeZone) {
            // Soft fade zone for clean anti-aliased edges
            const t = (minC - (threshold - fadeZone)) / fadeZone
            d[i + 3] = Math.round((1 - t) * d[i + 3])
          }
          // else: keep fully opaque
        }

        ctx.putImageData(imageData, 0, 0)
        resolve(canvas.toDataURL('image/png'))
      } catch {
        // Canvas tainted by CORS or other error → fall back to original URL
        resolve(url)
      }
    }

    img.onerror = () => resolve(url)
    img.src = url
  })
}

/**
 * Removes ONLY the outer background from an image using flood-fill (BFS from corners).
 * Unlike threshold-only approaches, this preserves interior white areas like a dog's
 * white chest — because they are NOT connected to the image edges.
 *
 * Algorithm:
 *   1. Seed BFS queue with all border pixels that are near-white.
 *   2. Expand to 4-connected neighbors that are also near-white.
 *   3. Make all visited pixels transparent.
 *   → Interior white islands (chest, eyes, etc.) are NEVER visited.
 */
export async function removeBackgroundFloodFill(
  url: string,
  threshold = 240,
): Promise<string> {
  return new Promise((resolve) => {
    const img = new window.Image()
    img.crossOrigin = 'anonymous'

    img.onload = () => {
      try {
        const W = img.naturalWidth
        const H = img.naturalHeight
        const canvas = document.createElement('canvas')
        canvas.width = W
        canvas.height = H
        const ctx = canvas.getContext('2d')!
        ctx.drawImage(img, 0, 0)

        const imageData = ctx.getImageData(0, 0, W, H)
        const d = imageData.data
        const visited = new Uint8Array(W * H)

        const isBackground = (idx4: number): boolean => {
          const a = d[idx4 + 3]
          if (a < 128) return false // already transparent — skip
          return Math.min(d[idx4], d[idx4 + 1], d[idx4 + 2]) >= threshold
        }

        // BFS with head-pointer queue (O(1) dequeue)
        const queue = new Int32Array(W * H)
        let head = 0
        let tail = 0

        const enqueue = (x: number, y: number) => {
          const idx = y * W + x
          if (visited[idx]) return
          if (!isBackground(idx * 4)) return
          visited[idx] = 1
          queue[tail++] = idx
        }

        // Seed from all 4 borders
        for (let x = 0; x < W; x++) {
          enqueue(x, 0)
          enqueue(x, H - 1)
        }
        for (let y = 1; y < H - 1; y++) {
          enqueue(0, y)
          enqueue(W - 1, y)
        }

        // BFS — remove connected background
        while (head < tail) {
          const idx = queue[head++]
          d[idx * 4 + 3] = 0
          const x = idx % W
          const y = Math.floor(idx / W)
          if (x > 0)     enqueue(x - 1, y)
          if (x < W - 1) enqueue(x + 1, y)
          if (y > 0)     enqueue(x,     y - 1)
          if (y < H - 1) enqueue(x,     y + 1)
        }

        ctx.putImageData(imageData, 0, 0)
        resolve(canvas.toDataURL('image/png'))
      } catch {
        resolve(url)
      }
    }

    img.onerror = () => resolve(url)
    img.src = url
  })
}

export async function compressAndResizeImage(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const img = new window.Image()
    const objectUrl = URL.createObjectURL(file)

    img.onload = () => {
      URL.revokeObjectURL(objectUrl)

      const MAX = 1024
      let { width, height } = img

      if (width > MAX || height > MAX) {
        if (width >= height) {
          height = Math.round((height * MAX) / width)
          width = MAX
        } else {
          width = Math.round((width * MAX) / height)
          height = MAX
        }
      }

      const canvas = document.createElement('canvas')
      canvas.width = width
      canvas.height = height
      const ctx = canvas.getContext('2d')!
      ctx.drawImage(img, 0, 0, width, height)

      // PNG preserves quality for edge detection; strip the data URI prefix
      const dataUrl = canvas.toDataURL('image/png')
      resolve(dataUrl.replace(/^data:image\/png;base64,/, ''))
    }

    img.onerror = () => reject(new Error('No se pudo cargar la imagen para comprimir'))
    img.src = objectUrl
  })
}